coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "src/**/*.test.{js,jsx,ts,tsx}"
  - "src/**/*.stories.{js,jsx,ts,tsx}"
  - "src/**/_*.{js,jsx,ts,tsx}"
  - "src/**/index.{js,jsx,ts,tsx}"
  - "src/**/*.config.{js,jsx,ts,tsx}"

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

codecov:
  require_ci_to_pass: yes 